#!/usr/bin/env python

import os
import numpy as np
from argparse import ArgumentParser

if __name__ == "__main__":
    ap = ArgumentParser()
    ap.add_argument('-w', '--wget_file', help='wget filename', default=f'../data/wget_list.txt')
    ap.add_argument("-o", "--outdir", help="output directory", default='./output')
    ap.add_argument("-v", "--verbose", action="store_true", default=False)
    ap.add_argument("-c", "--clobber", action="store_true", default=False)
    args = ap.parse_args()

    commands = []

    try:
        wget_list = np.loadtxt(args.wget_file, dtype=str)
    except:
        print(f"Error: {args.wget_file} not found!")

    for line in wget_list:
        kicid = line[2].split('/')[0][5:14]
        commands.append(f'./dl_kep {kicid} -o={args.outdir} -v')

    if not os.path.exists(args.outdir):
        os.makedirs(args.outdir)

    filename = 'dl_kep.batch'
    if not os.path.exists(filename) or args.clobber:
        np.savetxt(filename, commands, fmt='%s')
        # if args.verbose:
        print(f'Saved: {filename}\n')
        print(f'To run the batch file in parallel,\n$ cat {filename} | parallel\n')
    else:
        print(f'File exists: {filename}. Use --clobber to overwrite.')
